# pytest.ini
[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    courses: Тесты страницы курсов
    regression: Регрессионные тесты
    authorization: Тесты авторизации
    registration: Тесты регистрации
